import { z } from 'zod';
export const loginSchema = z.object({ email:z.string().email(), password:z.string().min(8) });
export const sessionCreateSchema = z.object({ moduleId:z.string().uuid(), date:z.string().datetime(), location:z.string().optional(), project:z.string().optional() });
export const attendancePostSchema = z.object({ attendees: z.array(z.object({ userId:z.string().uuid(), attended:z.boolean().optional() })).min(1) });
export const assessmentsPostSchema = z.object({ assessments: z.array(z.object({ userId:z.string().uuid(), competencyId:z.string().uuid(), outcome:z.enum(['COMPETENT','NEEDS_FOLLOWUP']), notes:z.string().optional() })).min(1) });
export const sessionAwardsPostSchema = z.object({ awards: z.array(z.object({ userId:z.string().uuid(), competencyId:z.string().uuid(), notes:z.string().optional() })).min(1) });
export const competencyCreateSchema = z.object({ code:z.string().min(3), title:z.string().min(3), category:z.string().min(2), description:z.string().optional(), expiryMonths:z.number().int().positive().optional() });
export const competencyPatchSchema = competencyCreateSchema.partial();
export const moduleCreateSchema = z.object({ title:z.string().min(3), mode:z.enum(['INDIVIDUAL','FACILITATED','HYBRID']).optional(), description:z.string().optional() });
export const modulePatchSchema = moduleCreateSchema.partial();
export const moduleCompetenciesPutSchema = z.object({ items: z.array(z.object({ competencyId:z.string().uuid(), evidenceType:z.enum(['COMPLETION','QUIZ','SESSION','SIGNOFF']) })).min(1) });
export const awardSchema = z.object({ userId:z.string().uuid(), evidenceType:z.enum(['COMPLETION','QUIZ','SESSION','SIGNOFF']), sessionId:z.string().uuid().optional(), notes:z.string().optional() });
